# Generated by Django 4.0.1 on 2022-02-19 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_posts_date_and_time_remove_posts_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='others_post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='Liked_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Liked_post', to='network.posts'),
        ),
        migrations.AddField(
            model_name='like',
            name='User_like',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='User_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
