# Generated by Django 3.2.7 on 2022-02-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_like_others_post_remove_like_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
