# Generated by Django 4.0.1 on 2022-04-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_posts_follows_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_id',
        ),
    ]
