# Generated by Django 4.0.1 on 2022-04-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_follow_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
