# Generated by Django 4.0.1 on 2022-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
