# Generated by Django 4.0.1 on 2022-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_follow_follower_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
